### ISSUE TITLE
Onjuiste HTML tag | dit hoort geen article te zijn

### ISSUE THREAD

**Issue by GekkeBoyJeff** [GekkeBoyJeff/TechGirlssss#3]
https://github.com/GekkeBoyJeff/TechGirlssss/blob/a77b24d073982bb48c46e5b67c6364850fd71586/views/partials/components/popularEvents.ejs#L6

In plaats van een article zou ik één van de volgende tags gebruiken:
1. div
2. ul + li

Als je de pagina nu opent zie je namelijk een article met 3 articles erin.
![image](https://github.com/GekkeBoyJeff/TechGirlssss/assets/74112414/d13b2d78-17bc-4aa4-a67d-d2e1c8c87853)

**Comment by TessaHeijnen** [comment]
Fixed ;)
